# Generated by Django 5.0.14 on 2026-06-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_seed_climber_equipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('climber', 'Climber'), ('treadmill', 'Treadmill'), ('bike', 'Stationary Bike'), ('elliptical', 'Elliptical'), ('rower', 'Rowing Machine'), ('other', 'Other')], max_length=50, verbose_name='Equipment type'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('in-service', 'In Service'), ('out-of-service', 'Out of Service')], default='in-service', max_length=20, verbose_name='Status'),
        ),
    ]
