# Generated by Django 5.0.14 on 2026-08-03 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0003_classprice_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="classprice",
            name="unique_current_classprice_per_slot",
        ),
        migrations.RemoveField(
            model_name="classprice",
            name="class_slot",
        ),
    ]
