# Generated by Django 5.0.14 on 2026-06-24 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_options_alter_client_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CC', 'Credit Card'), ('DC', 'Debit Card'), ('TRANSF', 'Electronic Transfer'), ('PAPP', 'Payments App')], max_length=20, verbose_name='Payment type')),
                ('payment_identifier', models.CharField(max_length=50, unique=True, verbose_name='Payment identifier')),
                ('date', models.DateField(verbose_name='Date')),
                ('class_slot_count', models.PositiveSmallIntegerField(verbose_name='Class slot count')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='payments/evidence/', verbose_name='Evidence')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_payments', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['client', '-date'], name='payments_pa_client__9f874c_idx'), models.Index(fields=['date', 'payment_type'], name='payments_pa_date_12743b_idx')],
            },
        ),
    ]
