# Generated by Django 5.0.14 on 2026-08-03 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentreservation'),
        ('reservations', '0004_reservation_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreservation',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='reservations.reservation', verbose_name='Reservation'),
        ),
    ]
